// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF9MfdpTdoPXv-KJPsnYYql6DxN4Xny0E',
    appId: '1:56245991050:web:9e8df3bd33a0150ee99f73',
    messagingSenderId: '56245991050',
    projectId: 'dareme-app-eec44',
    authDomain: 'dareme-app-eec44.firebaseapp.com',
    storageBucket: 'dareme-app-eec44.firebasestorage.app',
    measurementId: 'G-M17E6309X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp9d-f0mcqnMhX2K0Z-IQyjBdaVPS4hDE',
    appId: '1:56245991050:android:1185c047b41ea825e99f73',
    messagingSenderId: '56245991050',
    projectId: 'dareme-app-eec44',
    storageBucket: 'dareme-app-eec44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg5NN-EAPOoM-ZjoJJbgAcvaXnwsipY58',
    appId: '1:56245991050:ios:b80182329fe4efe8e99f73',
    messagingSenderId: '56245991050',
    projectId: 'dareme-app-eec44',
    storageBucket: 'dareme-app-eec44.firebasestorage.app',
    iosBundleId: 'com.example.hyroxChallenges',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg5NN-EAPOoM-ZjoJJbgAcvaXnwsipY58',
    appId: '1:56245991050:ios:b80182329fe4efe8e99f73',
    messagingSenderId: '56245991050',
    projectId: 'dareme-app-eec44',
    storageBucket: 'dareme-app-eec44.firebasestorage.app',
    iosBundleId: 'com.example.hyroxChallenges',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF9MfdpTdoPXv-KJPsnYYql6DxN4Xny0E',
    appId: '1:56245991050:web:03419b7ef88bb22ae99f73',
    messagingSenderId: '56245991050',
    projectId: 'dareme-app-eec44',
    authDomain: 'dareme-app-eec44.firebaseapp.com',
    storageBucket: 'dareme-app-eec44.firebasestorage.app',
    measurementId: 'G-WSXX66YTM6',
  );
}
